---
- name: File Modules Understanding
  hosts: all
  become: yes
  tasks:
    - name: Copy using inline content
      copy:
         content: 'This server infrastructure is managed by ansible'
         dest: /etc/motd

    - name: Create a directory if it does not exist
      file:
        path: /opt/test21
        state: directory
        mode: '0755'

