---
- name: Install Apache2 on Ubuntu
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install apache2
      apt:
        name: apache2
        state: present

    - name: Enable apache2 to start on boot
      systemd:
        name: apache2
        enabled: yes

    - name: Start apache2 service
      systemd:
        name: apache2
         enabled: yes

    - name: Start apache2 service
      systemd:
        name: apache2
        state: started

    - name: Copy files to web servers
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        backup: yes


